using System.Text.Json.Serialization;
using LichessSharp.Api;
using LichessSharp.Api.Contracts;
using LichessSharp.Models.Account;
using LichessSharp.Models.Common;
using LichessSharp.Models.Fide;
using LichessSharp.Models.Games;
using LichessSharp.Models.Puzzles;
using LichessSharp.Models.Users;

namespace LichessSharp.Serialization;

/// <summary>
///     Source-generated JSON serialization context for AOT compatibility.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNameCaseInsensitive = true,
    WriteIndented = false)]
// Common types
[JsonSerializable(typeof(LightUser))]
[JsonSerializable(typeof(Clock))]
[JsonSerializable(typeof(Opening))]
[JsonSerializable(typeof(PerformanceType))]
[JsonSerializable(typeof(OkResponse))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(EmailResponse))]
[JsonSerializable(typeof(KidModeResponse))]
[JsonSerializable(typeof(NoteResponse))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
// User types
[JsonSerializable(typeof(User))]
[JsonSerializable(typeof(UserExtended))]
[JsonSerializable(typeof(UserStatus))]
[JsonSerializable(typeof(UserStatus[]))]
[JsonSerializable(typeof(List<User>))]
[JsonSerializable(typeof(List<UserStatus>))]
[JsonSerializable(typeof(UserProfile))]
[JsonSerializable(typeof(PerfStats))]
[JsonSerializable(typeof(PlayTime))]
[JsonSerializable(typeof(GameCount))]
[JsonSerializable(typeof(Dictionary<string, List<User>>))]
[JsonSerializable(typeof(List<RatingHistory>))]
[JsonSerializable(typeof(RatingHistory))]
[JsonSerializable(typeof(LeaderboardResponse))]
// User Performance types
[JsonSerializable(typeof(UserPerformance))]
[JsonSerializable(typeof(PerformanceStatistics))]
[JsonSerializable(typeof(RatingAtTime))]
[JsonSerializable(typeof(ResultsVsOpponents))]
[JsonSerializable(typeof(OpponentResult))]
[JsonSerializable(typeof(PerformanceCount))]
[JsonSerializable(typeof(ResultStreak))]
[JsonSerializable(typeof(StreakInfo))]
[JsonSerializable(typeof(StreakValue))]
[JsonSerializable(typeof(PlayStreak))]
// User Activity types
[JsonSerializable(typeof(UserActivity))]
[JsonSerializable(typeof(List<UserActivity>))]
[JsonSerializable(typeof(ActivityInterval))]
[JsonSerializable(typeof(ActivityGames))]
[JsonSerializable(typeof(ActivityPuzzles))]
[JsonSerializable(typeof(ActivityScore))]
[JsonSerializable(typeof(ActivityRatingProgress))]
[JsonSerializable(typeof(ActivityTournaments))]
[JsonSerializable(typeof(ActivityPractice))]
[JsonSerializable(typeof(ActivityCorrespondence))]
[JsonSerializable(typeof(ActivityCorrespondenceGame))]
[JsonSerializable(typeof(ActivityCorrespondenceEnds))]
[JsonSerializable(typeof(ActivityFollows))]
[JsonSerializable(typeof(ActivityFollowList))]
[JsonSerializable(typeof(ActivityStudy))]
[JsonSerializable(typeof(ActivityTeam))]
[JsonSerializable(typeof(ActivityPost))]
// User Social types
[JsonSerializable(typeof(Crosstable))]
[JsonSerializable(typeof(CrosstableMatchup))]
[JsonSerializable(typeof(Streamer))]
[JsonSerializable(typeof(List<Streamer>))]
[JsonSerializable(typeof(StreamInfo))]
[JsonSerializable(typeof(StreamerInfo))]
[JsonSerializable(typeof(StreamChannel))]
[JsonSerializable(typeof(Timeline))]
[JsonSerializable(typeof(TimelineEntry))]
[JsonSerializable(typeof(TimelineData))]
[JsonSerializable(typeof(AutocompletePlayer))]
[JsonSerializable(typeof(AutocompleteResponse))]
[JsonSerializable(typeof(List<AutocompletePlayer>))]
[JsonSerializable(typeof(List<string>))]
// Account types
[JsonSerializable(typeof(AccountPreferences))]
[JsonSerializable(typeof(UserPreferences))]
// Game types
[JsonSerializable(typeof(Game))]
[JsonSerializable(typeof(GameJson))]
[JsonSerializable(typeof(GamePlayers))]
[JsonSerializable(typeof(GamePlayer))]
[JsonSerializable(typeof(VariantInfo))]
[JsonSerializable(typeof(List<Game>))]
// Ongoing Game types
[JsonSerializable(typeof(OngoingGamesResponse))]
[JsonSerializable(typeof(OngoingGame))]
[JsonSerializable(typeof(OngoingGameOpponent))]
// Game Analysis types
[JsonSerializable(typeof(PlayerAnalysis))]
[JsonSerializable(typeof(Analysis))]
[JsonSerializable(typeof(Judgment))]
// Import Game types
[JsonSerializable(typeof(ImportGameResponse))]
// Game Stream types
[JsonSerializable(typeof(MoveStreamEvent))]
[JsonSerializable(typeof(List<MoveStreamEvent>))]
[JsonSerializable(typeof(GameStreamEvent))]
[JsonSerializable(typeof(List<GameStreamEvent>))]
[JsonSerializable(typeof(GameStreamPlayers))]
[JsonSerializable(typeof(GameStreamPlayer))]
// Cloud/Explorer types
[JsonSerializable(typeof(CloudEvaluation))]
[JsonSerializable(typeof(PrincipalVariation))]
[JsonSerializable(typeof(ExplorerResult))]
[JsonSerializable(typeof(ExplorerMove))]
[JsonSerializable(typeof(ExplorerGame))]
[JsonSerializable(typeof(ExplorerOpening))]
[JsonSerializable(typeof(TablebaseResult))]
[JsonSerializable(typeof(TablebaseMove))]
// Puzzle types
[JsonSerializable(typeof(Puzzle))]
[JsonSerializable(typeof(PuzzleWithGame))]
[JsonSerializable(typeof(PuzzleGame))]
[JsonSerializable(typeof(PuzzlePlayer))]
[JsonSerializable(typeof(PuzzleActivity))]
[JsonSerializable(typeof(PuzzleActivityPuzzle))]
[JsonSerializable(typeof(PuzzleDashboard))]
[JsonSerializable(typeof(PuzzleThemeResults))]
[JsonSerializable(typeof(PuzzlePerformance))]
[JsonSerializable(typeof(StormDashboard))]
[JsonSerializable(typeof(StormHigh))]
[JsonSerializable(typeof(StormDay))]
[JsonSerializable(typeof(PuzzleRace))]
// Puzzle Batch types
[JsonSerializable(typeof(PuzzleGlicko))]
[JsonSerializable(typeof(PuzzleBatch))]
[JsonSerializable(typeof(PuzzleSolution))]
[JsonSerializable(typeof(PuzzleRound))]
[JsonSerializable(typeof(PuzzleBatchResult))]
[JsonSerializable(typeof(PuzzleBatchSolveRequest))]
[JsonSerializable(typeof(List<PuzzleSolution>))]
[JsonSerializable(typeof(List<PuzzleRound>))]
// Puzzle Race types
[JsonSerializable(typeof(PuzzleReplayInfo))]
[JsonSerializable(typeof(PuzzleAngle))]
[JsonSerializable(typeof(PuzzleReplay))]
[JsonSerializable(typeof(PuzzleRacePlayer))]
[JsonSerializable(typeof(PuzzleRaceResults))]
[JsonSerializable(typeof(List<PuzzleRacePlayer>))]
// FIDE types
[JsonSerializable(typeof(FidePlayer))]
[JsonSerializable(typeof(List<FidePlayer>))]
// TV API types
[JsonSerializable(typeof(TvChannels))]
[JsonSerializable(typeof(TvGame))]
[JsonSerializable(typeof(TvUser))]
[JsonSerializable(typeof(TvFeedEvent))]
[JsonSerializable(typeof(TvFeedData))]
[JsonSerializable(typeof(TvFeedPlayer))]
[JsonSerializable(typeof(List<TvFeedPlayer>))]
// Challenges API types
[JsonSerializable(typeof(ChallengeList))]
[JsonSerializable(typeof(ChallengeJson))]
[JsonSerializable(typeof(ChallengeUser))]
[JsonSerializable(typeof(ChallengeVariant))]
[JsonSerializable(typeof(ChallengeTimeControl))]
[JsonSerializable(typeof(ChallengePerf))]
[JsonSerializable(typeof(ChallengeOpenJson))]
[JsonSerializable(typeof(ChallengeAiResponse))]
[JsonSerializable(typeof(ChallengeAiGameStatus))]
[JsonSerializable(typeof(List<ChallengeJson>))]
// Board API types
[JsonSerializable(typeof(BoardAccountEvent))]
[JsonSerializable(typeof(BoardAccountGameInfo))]
[JsonSerializable(typeof(BoardGameStatus))]
[JsonSerializable(typeof(BoardVariant))]
[JsonSerializable(typeof(BoardOpponent))]
[JsonSerializable(typeof(BoardCompat))]
[JsonSerializable(typeof(BoardGameEvent))]
[JsonSerializable(typeof(GameFullEvent))]
[JsonSerializable(typeof(GameStateEvent))]
[JsonSerializable(typeof(ChatLineEvent))]
[JsonSerializable(typeof(OpponentGoneEvent))]
[JsonSerializable(typeof(BoardClock))]
[JsonSerializable(typeof(BoardPerf))]
[JsonSerializable(typeof(BoardPlayer))]
[JsonSerializable(typeof(ChatMessage))]
[JsonSerializable(typeof(List<ChatMessage>))]
[JsonSerializable(typeof(SeekResult))]
// Bot API types
[JsonSerializable(typeof(BotAccountEvent))]
[JsonSerializable(typeof(BotAccountGameInfo))]
[JsonSerializable(typeof(BotGameStatus))]
[JsonSerializable(typeof(BotVariant))]
[JsonSerializable(typeof(BotOpponent))]
[JsonSerializable(typeof(BotCompat))]
[JsonSerializable(typeof(BotGameEvent))]
[JsonSerializable(typeof(BotGameFullEvent))]
[JsonSerializable(typeof(BotGameStateEvent))]
[JsonSerializable(typeof(BotChatLineEvent))]
[JsonSerializable(typeof(BotOpponentGoneEvent))]
[JsonSerializable(typeof(BotClock))]
[JsonSerializable(typeof(BotPerf))]
[JsonSerializable(typeof(BotPlayer))]
[JsonSerializable(typeof(BotUser))]
[JsonSerializable(typeof(BotPerfs))]
[JsonSerializable(typeof(BotPerfStats))]
[JsonSerializable(typeof(BotPlayTime))]
// Teams API types
[JsonSerializable(typeof(Team))]
[JsonSerializable(typeof(TeamLeader))]
[JsonSerializable(typeof(TeamPaginator))]
[JsonSerializable(typeof(TeamMember))]
[JsonSerializable(typeof(TeamMemberPerfs))]
[JsonSerializable(typeof(TeamMemberPerfStats))]
[JsonSerializable(typeof(TeamRequest))]
[JsonSerializable(typeof(TeamRequestWithUser))]
[JsonSerializable(typeof(TeamRequestUser))]
[JsonSerializable(typeof(TeamPlayTime))]
[JsonSerializable(typeof(List<Team>))]
[JsonSerializable(typeof(List<TeamLeader>))]
[JsonSerializable(typeof(List<TeamRequestWithUser>))]
// Arena Tournaments API types
[JsonSerializable(typeof(ArenaTournamentList))]
[JsonSerializable(typeof(ArenaTournamentSummary))]
[JsonSerializable(typeof(ArenaTournament))]
[JsonSerializable(typeof(ArenaClock))]
[JsonSerializable(typeof(ArenaVariant))]
[JsonSerializable(typeof(ArenaPerf))]
[JsonSerializable(typeof(ArenaRatingRestriction))]
[JsonSerializable(typeof(ArenaTeamBattle))]
[JsonSerializable(typeof(ArenaWinner))]
[JsonSerializable(typeof(ArenaPosition))]
[JsonSerializable(typeof(ArenaVerdicts))]
[JsonSerializable(typeof(ArenaVerdict))]
[JsonSerializable(typeof(ArenaQuote))]
[JsonSerializable(typeof(ArenaSpotlight))]
[JsonSerializable(typeof(ArenaTournamentMe))]
[JsonSerializable(typeof(ArenaStanding))]
[JsonSerializable(typeof(ArenaStandingPlayer))]
[JsonSerializable(typeof(ArenaSheet))]
[JsonSerializable(typeof(ArenaPodiumPlayer))]
[JsonSerializable(typeof(ArenaPodiumNb))]
[JsonSerializable(typeof(ArenaFeaturedGame))]
[JsonSerializable(typeof(ArenaFeaturedPlayer))]
[JsonSerializable(typeof(ArenaDuel))]
[JsonSerializable(typeof(ArenaDuelPlayer))]
[JsonSerializable(typeof(ArenaDuelTeams))]
[JsonSerializable(typeof(ArenaGreatPlayer))]
[JsonSerializable(typeof(ArenaPlayerResult))]
[JsonSerializable(typeof(ArenaTeamStanding))]
[JsonSerializable(typeof(ArenaTeamResult))]
[JsonSerializable(typeof(ArenaTeamPlayer))]
[JsonSerializable(typeof(ArenaTeamPlayerUser))]
[JsonSerializable(typeof(ArenaPlayedTournament))]
[JsonSerializable(typeof(ArenaPlayedPlayer))]
[JsonSerializable(typeof(List<ArenaTournamentSummary>))]
[JsonSerializable(typeof(List<ArenaVerdict>))]
[JsonSerializable(typeof(List<ArenaStandingPlayer>))]
[JsonSerializable(typeof(List<ArenaPodiumPlayer>))]
[JsonSerializable(typeof(List<ArenaDuel>))]
[JsonSerializable(typeof(List<ArenaDuelPlayer>))]
[JsonSerializable(typeof(List<ArenaTeamResult>))]
[JsonSerializable(typeof(List<ArenaTeamPlayer>))]
// Swiss Tournaments API types
[JsonSerializable(typeof(SwissTournament))]
[JsonSerializable(typeof(SwissClock))]
[JsonSerializable(typeof(SwissVerdicts))]
[JsonSerializable(typeof(SwissVerdict))]
[JsonSerializable(typeof(SwissStats))]
[JsonSerializable(typeof(SwissNextRound))]
[JsonSerializable(typeof(SwissPlayerResult))]
[JsonSerializable(typeof(List<SwissVerdict>))]
// Simuls API types
[JsonSerializable(typeof(SimulList))]
[JsonSerializable(typeof(Simul))]
[JsonSerializable(typeof(SimulHost))]
[JsonSerializable(typeof(SimulVariant))]
[JsonSerializable(typeof(List<Simul>))]
// Studies API types
[JsonSerializable(typeof(StudyMetadata))]
[JsonSerializable(typeof(StudyImportResult))]
[JsonSerializable(typeof(StudyChapter))]
[JsonSerializable(typeof(StudyChapterPlayer))]
[JsonSerializable(typeof(List<StudyChapter>))]
// Broadcasts API types
[JsonSerializable(typeof(BroadcastTour))]
[JsonSerializable(typeof(BroadcastTourInfo))]
[JsonSerializable(typeof(BroadcastRoundInfo))]
[JsonSerializable(typeof(BroadcastWithRounds))]
[JsonSerializable(typeof(BroadcastGroup))]
[JsonSerializable(typeof(BroadcastGroupTour))]
[JsonSerializable(typeof(BroadcastRound))]
[JsonSerializable(typeof(BroadcastRoundStudyInfo))]
[JsonSerializable(typeof(BroadcastStudyFeatures))]
[JsonSerializable(typeof(BroadcastRoundGame))]
[JsonSerializable(typeof(BroadcastGamePlayer))]
[JsonSerializable(typeof(BroadcastWithLastRound))]
[JsonSerializable(typeof(BroadcastTopPage))]
[JsonSerializable(typeof(BroadcastPagination))]
[JsonSerializable(typeof(BroadcastSearchPage))]
[JsonSerializable(typeof(BroadcastByUser))]
[JsonSerializable(typeof(BroadcastRoundNew))]
[JsonSerializable(typeof(BroadcastMyRound))]
[JsonSerializable(typeof(BroadcastPgnPushResult))]
[JsonSerializable(typeof(BroadcastPgnPushGame))]
[JsonSerializable(typeof(List<BroadcastRoundInfo>))]
[JsonSerializable(typeof(List<BroadcastRoundGame>))]
[JsonSerializable(typeof(List<BroadcastWithLastRound>))]
[JsonSerializable(typeof(List<BroadcastGroupTour>))]
[JsonSerializable(typeof(List<BroadcastGamePlayer>))]
[JsonSerializable(typeof(List<BroadcastPgnPushGame>))]
[JsonSerializable(typeof(BroadcastPlayerEntry))]
[JsonSerializable(typeof(List<BroadcastPlayerEntry>))]
[JsonSerializable(typeof(BroadcastPlayerTiebreak))]
[JsonSerializable(typeof(List<BroadcastPlayerTiebreak>))]
[JsonSerializable(typeof(BroadcastPlayerWithGames))]
[JsonSerializable(typeof(BroadcastPlayerFide))]
[JsonSerializable(typeof(BroadcastPlayerFideRatings))]
[JsonSerializable(typeof(BroadcastPlayerGame))]
[JsonSerializable(typeof(List<BroadcastPlayerGame>))]
[JsonSerializable(typeof(BroadcastPlayerOpponent))]
// Bulk Pairings API types
[JsonSerializable(typeof(BulkPairingListResponse))]
[JsonSerializable(typeof(BulkPairing))]
[JsonSerializable(typeof(BulkPairingGame))]
[JsonSerializable(typeof(BulkPairingClock))]
[JsonSerializable(typeof(List<BulkPairing>))]
[JsonSerializable(typeof(List<BulkPairingGame>))]
// Messaging API types
[JsonSerializable(typeof(MessageSentResponse))]
internal partial class LichessJsonContext : JsonSerializerContext
{
}