using System.Text.Json;
using System.Text.Json.Serialization;
using LichessSharp.Api;
using LichessSharp.Models;

namespace LichessSharp.Serialization;

/// <summary>
/// Source-generated JSON serialization context for AOT compatibility.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNameCaseInsensitive = true,
    WriteIndented = false)]
[JsonSerializable(typeof(User))]
[JsonSerializable(typeof(UserExtended))]
[JsonSerializable(typeof(UserStatus))]
[JsonSerializable(typeof(UserStatus[]))]
[JsonSerializable(typeof(List<User>))]
[JsonSerializable(typeof(List<UserStatus>))]
[JsonSerializable(typeof(AccountPreferences))]
[JsonSerializable(typeof(Game))]
[JsonSerializable(typeof(GameJson))]
[JsonSerializable(typeof(GameUser))]
[JsonSerializable(typeof(List<Game>))]
[JsonSerializable(typeof(Puzzle))]
[JsonSerializable(typeof(PuzzleWithGame))]
[JsonSerializable(typeof(Models.OkResponse))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(EmailResponse))]
[JsonSerializable(typeof(KidModeResponse))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(Dictionary<string, List<User>>))]
[JsonSerializable(typeof(List<RatingHistory>))]
[JsonSerializable(typeof(RatingHistory))]
[JsonSerializable(typeof(LeaderboardResponse))]
[JsonSerializable(typeof(CloudEvaluation))]
[JsonSerializable(typeof(PrincipalVariation))]
[JsonSerializable(typeof(ExplorerResult))]
[JsonSerializable(typeof(ExplorerMove))]
[JsonSerializable(typeof(ExplorerGame))]
[JsonSerializable(typeof(ExplorerOpening))]
[JsonSerializable(typeof(TablebaseResult))]
[JsonSerializable(typeof(TablebaseMove))]
[JsonSerializable(typeof(OngoingGamesResponse))]
[JsonSerializable(typeof(OngoingGame))]
[JsonSerializable(typeof(ImportGameResponse))]
[JsonSerializable(typeof(PuzzleActivity))]
[JsonSerializable(typeof(PuzzleActivityPuzzle))]
[JsonSerializable(typeof(PuzzleDashboard))]
[JsonSerializable(typeof(PuzzleThemeResults))]
[JsonSerializable(typeof(PuzzlePerformance))]
[JsonSerializable(typeof(StormDashboard))]
[JsonSerializable(typeof(StormHigh))]
[JsonSerializable(typeof(StormDay))]
[JsonSerializable(typeof(PuzzleRace))]
// TV API types
[JsonSerializable(typeof(TvChannels))]
[JsonSerializable(typeof(TvGame))]
[JsonSerializable(typeof(TvUser))]
[JsonSerializable(typeof(TvFeedEvent))]
[JsonSerializable(typeof(TvFeedData))]
[JsonSerializable(typeof(TvFeedPlayer))]
[JsonSerializable(typeof(List<TvFeedPlayer>))]
// Challenges API types
[JsonSerializable(typeof(ChallengeList))]
[JsonSerializable(typeof(ChallengeJson))]
[JsonSerializable(typeof(ChallengeUser))]
[JsonSerializable(typeof(ChallengeVariant))]
[JsonSerializable(typeof(ChallengeTimeControl))]
[JsonSerializable(typeof(ChallengePerf))]
[JsonSerializable(typeof(ChallengeOpenJson))]
[JsonSerializable(typeof(ChallengeAiResponse))]
[JsonSerializable(typeof(ChallengeAiGameStatus))]
[JsonSerializable(typeof(List<ChallengeJson>))]
// Board API types
[JsonSerializable(typeof(BoardAccountEvent))]
[JsonSerializable(typeof(BoardAccountGameInfo))]
[JsonSerializable(typeof(BoardGameStatus))]
[JsonSerializable(typeof(BoardVariant))]
[JsonSerializable(typeof(BoardOpponent))]
[JsonSerializable(typeof(BoardCompat))]
[JsonSerializable(typeof(BoardGameEvent))]
[JsonSerializable(typeof(GameFullEvent))]
[JsonSerializable(typeof(GameStateEvent))]
[JsonSerializable(typeof(ChatLineEvent))]
[JsonSerializable(typeof(OpponentGoneEvent))]
[JsonSerializable(typeof(BoardClock))]
[JsonSerializable(typeof(BoardPerf))]
[JsonSerializable(typeof(BoardPlayer))]
[JsonSerializable(typeof(ChatMessage))]
[JsonSerializable(typeof(List<ChatMessage>))]
[JsonSerializable(typeof(SeekResult))]
// Bot API types
[JsonSerializable(typeof(BotAccountEvent))]
[JsonSerializable(typeof(BotAccountGameInfo))]
[JsonSerializable(typeof(BotGameStatus))]
[JsonSerializable(typeof(BotVariant))]
[JsonSerializable(typeof(BotOpponent))]
[JsonSerializable(typeof(BotCompat))]
[JsonSerializable(typeof(BotGameEvent))]
[JsonSerializable(typeof(BotGameFullEvent))]
[JsonSerializable(typeof(BotGameStateEvent))]
[JsonSerializable(typeof(BotChatLineEvent))]
[JsonSerializable(typeof(BotOpponentGoneEvent))]
[JsonSerializable(typeof(BotClock))]
[JsonSerializable(typeof(BotPerf))]
[JsonSerializable(typeof(BotPlayer))]
[JsonSerializable(typeof(BotUser))]
[JsonSerializable(typeof(BotPerfs))]
[JsonSerializable(typeof(BotPerfStats))]
[JsonSerializable(typeof(BotPlayTime))]
internal partial class LichessJsonContext : JsonSerializerContext
{
}
